title: jac08h
description: >- 
    <a href='/index'>Home</a> | <a href='/programming'>Programming</a> | <a href='/connect_with_me'>Connect With Me</a>
    
github_username:  jac08h

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
