title: jh
description: >-
  <a href='/index'>Home</a> | <a href='/projects'>Projects</a> | <a href='/books'>Books</a> | <a href='https://unpredictabletokens.substack.com'>Blog</a> @ Substack | <a href='/contact'>Contact</a>

github_username: jac08h

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
